on: [push]

jobs:
  hello_world_jobs:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: hello world action steps
        id: hello
        uses: mirajhad/ECOM.WEB
        with:
          who-to-greet: 'Miraj'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
